#!/bin/bash

# this shows how to target an arbitrary NST window using `xprop` and forward
# its history buffer to `gvim`.
#
# this is a pull method that doesn't require adjusting NST's configuration.

NST_MSG=`which nst-msg`

if [ -z "$NST_MSG" ]; then
	echo "Missing 'nst-msg' in PATH. Cannot continue." 1>&2
	exit 1
fi

PID=`xprop | grep _NET_WM_PID | cut -d '=' -f 2 | tr -d ' '`
exec $NST_MSG -p $PID -d | gvim -
