#!/bin/bash

# this shows how to target an arbitrary NST window using `xprop` and forward
# its history buffer to `gvim`.
#
# this is a pull method that doesn't require adjusting NST's configuration.

PID=`xprop | grep _NET_WM_PID | cut -d '=' -f 2 | tr -d ' '`
exec nst-msg -p $PID -d | gvim -
