'\" t
.\"     Title: nst-msg
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 10/26/2024
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "NST\-MSG" "1" "10/26/2024" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nst-msg \- send message to nst terminal emulator
.SH "SYNOPSIS"
.sp
nst\-msg [\-S] [\-s] [\-d] [\-D] [\-t] [\-\-cwds]
.SH "DESCRIPTION"
.sp
nst\-msg is a tool to interact with running nst(1) terminal emulator instances\&.
.sp
Most commands target the currently running terminal which is identified by the \fBNST_IPC_ADDR\fR environment variable that is automatically set by nst\&. Some commands are global and target all terminal instances accessible by the calling user\&.
.SH "OPTIONS"
.PP
\fB\-S\fR, \fB\-\-snapshot\fR
.RS 4
save snapshot of the current terminal history\&. The snapshot can later be retrieved via \-s\&.
.RE
.PP
\fB\-s\fR, \fB\-\-get\-snapshot\fR
.RS 4
Print the data stored during the last snapshot operation (\-S) to stdout\&. If no snapshot is available then nothing is printed\&.
.RE
.PP
\fB\-d\fR, \fB\-\-get\-history\fR
.RS 4
Print (dump) the current terminal history buffer to stdout\&. This always operates on the main screen, not on the alt screen of the terminal\&.
.RE
.PP
\fB\-D\fR, \fB\-\-get\-global\-history\fR
.RS 4
Like \-d but prints the concatenated history of all accessible nst instances to stdout\&. This can be used to search for data lost in one of many terminal instances\&.
.RE
.PP
\fB\-t\fR, \fB\-\-test\fR
.RS 4
Performs a connection test to the associated nst terminal emulator instance\&. If the connection succeeds then an exit status of zero is returned, non\-zero otherwise\&. This can be used to determine whether an nst terminal is associated at all\&.
.RE
.PP
\fB\-\-cwds\fR
.RS 4
This retrieves the current working directories of the child processes of all reachable nst instances\&. One CWD is printed per line, and only unique entries are printed\&. This does not currently support the exotic case that the CWD may contain a newline character\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print the nst\-msg version number and exists\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print a usage text\&.
.RE
.SH "EXIT CODES"
.PP
0
.RS 4
Success\&.
.RE
.PP
1
.RS 4
Other errors\&.
.RE
.PP
2
.RS 4
Error connecting to one or more NST instances\&.
.RE
.PP
3
.RS 4
One or more NST instances reported an error on protocol level\&.
.RE
.PP
5
.RS 4
Internal or logical error\&.
.RE
.SH "AUTHORS"
.sp
See the LICENSE file for the authors\&.
.SH "LICENSE"
.sp
See the LICENSE file for the terms of redistribution\&.
