NST(1)
======

== Name
nst - not (so) simple terminal

== Synopsis
nst  [-l <path-to-tty>] [-w <window-id>] [-o <iofile>] [-f <fontconfig font name>] [-g <X11 gemeoetry>] [-t <title>] [-n <name>] [-c <class>] [-e] [-i] [-a] [--] [--version] [-h] [command [arguments...]]

== Description
nst is a (not so) simple terminal emulator.

This is a C++ port and fork of the suckless.org ST simple terminal emulator.

== Options

*-a, --no-alt-screen*::
  disable the alternative screen buffer in the terminal.

*-c, --window-class*::
  defines the window class (defaults to $TERM).

*-f, --font*::
  defines the font to use when nst is run. This is a fontconfig string like
  "LiberationMono:pixelsize=18:antialias=true:autohint=true".

*-g, --geometry*::
  defines the X11 geometry string. The form is [=][<cols>{xX}<rows>][{+-}<xoffset>{+-}<yoffset>].
  See XParseGeometry(3) for further details.

*-i, --fixed-geometry*::
  fixate the window position with the -g option.

*-n, --window-name*::
  defines the window instance name (WM_CLASS property, default $TERM).

*-o, --iofile*::
  writes all the raw I/O to the given file for recording. "-" means stdout.

*-t, --window-title*::
  defines the window title (default "nst").

*-w, --embed-window*::
  embeds nst within the window identifier by window-id.

*-l --tty*::
  use a tty line instead of pseudo terminal. Remaining parameters will be
  passed as flags to stty(1). path-to-tty should be a (pseudo-)serial device (e.g.
  /dev/ttyS0 on Linux for serial port 0). By default nst initializes the
  serial line to 8 bits, no parity, 1 stop bit and a 38400 baud rate. The speed
  is set by appending it as  last argument  (e.g.  "nst  -l  /dev/ttyS0 115200").
  Arguments before the last one are stty(1) flags. If you want to set odd parity
  on 115200 baud use for example "nst -l /dev/ttyS0 parenb parodd 115200".  Set
  the number of bits by using  for example "nst -l /dev/ttyS0 cs7 115200". See
  stty(1) for more arguments and cases.

*--version*::
  prints version information and exits.

*-e*::
  execute remaining parameters instead of the shell. This switch is not
  actually needed, it is only for backwards compatibility. The remaining
  parameters will be used even without this switch, except if -l is given.

== Shortcuts

Break::
  Sends a break in the serial line. The break key is obtained in PC keyboards pressing at the same time control and pause.

Ctrl-Print Screen::
  Toggles if nst should print to the iofile.

Shift-Print Screen::
  Prints the full screen to the iofile.

Print Screen::
  Prints the selection to the iofile.

Ctrl-Scroll Wheel Up::
  Increases font size.

Ctrl-Scroll Wheel Down::
  Decreases font size.

Shift-Mod1-Home::
  Resets to default font size.

Ctrl-Shift-Home::
  Jumps to end of history (oldest) position.

Ctrl-Shift-End::
  Jumps to current screen.

Shift-Page Up::
  Scrolls history up by 10 lines.

Shift-Page Down::
  Scrolls history down by 10 lines.

Ctrl-Shift-Page Up::
  Scrolls history up by half a screen.

Ctrl-Shift-Page Down::
  Scrolls history down by half a screen.

Ctrl-Shift-y::
  Pastes from primary selection (middle mouse button).

Ctrl-Shift-c::
  Copies the selected text to the clipboard selection.

Ctrl-Shift-v::
  Pastes from the clipboard selection.

Ctrl-Shift-Keypad Div::
  Inverts the color scheme.

Ctrl-Shift-B::
  Invokes an external program and pipes the current history buffer to it (gvim
  by default).

== Customization

nst can be customized by adjuting the nst_config.hxx and/or nst_config.cxx
files and (re)compiling the source code. This keeps it fast, secure and
simple.

== Authors

See the LICENSE file for the authors.

== License

See the LICENSE file for the terms of redistribution.
