nst.conf(5)
===========

== Name
nst.conf - nst(1) configuration file

== Description

nst.conf is the configuration file for the nst(1) terminal emulator. It allows
to change a range of settings to override the compiled-in defaults during
runtime.

The configuration file is read once during startup of nst(1). Multiple
configuration files will be looked up in the following order:

- /etc/nst.conf for system wide configuration.
- $HOME/.config/nst.conf for user specific configuration.
- the file specified via the --config command line switch.
- the file specified in the NST_CONFIG environment variable.

The settings found in the configuration files are accumulated. Settings from
configuration files that are parsed at a later time will override previously
seen settings, if they overlap.

The configuration file is parsed line by line. Lines starting with a
"#" character (after stripping leading whitespace) will be treated as comments
and will be ignored. There is no support for line continuation neither in
comments nor in configuration lines.

All configuration lines follow the format "<key> = <value>". <key> is an
alphanumerical string containing only ASCII characters, underscores and no
whitespace. Leading and trailing whitespace is stripped. <key> items that are
unknown to nst(1) will be parsed for syntax errors but will be ignored
otherwise. <value> can be of one of the following formats, depending on the
configuration <key>:

- a UTF8 encoded unicode string surrounded by double quotes. To embed double
  quotes in the string, minimal backslash escape sequences are supported, namely
  \" to embed a double quote and \\ to embed a literal backslash character.
- an unsigned 32-bit integer consisting of only numerical characters.
- a boolean value consisting either of the string true or false (without
  using quotes).

Parse errors will be diagnosed by nst(1) on stderr, but will not cause the
terminal emulator to abort. Bad configuration settings (on a logical level)
can still lead to a non-functional nst(1).

The available configuration keys along with a description and their
compiled-in defaults can be found in the template configuration file installed
in /etc/nst.conf.

== FILES

/etc/nst.conf
$HOME/.config/nst.conf
