Import('env')

doc_env = env.Clone()

# doxygen

if env['build_docs']:
    doxy_cmd = doc_env.Command(
        'doxygen/html/index.html',
        'doxygen.conf',
        action='doxygen -q $SOURCE')
    env.AlwaysBuild(doxy_cmd)
    env.Alias('doxygen', doxy_cmd)

# man page

# this is generated in the source tree!
nst_man_cmd = doc_env.Command(
    '#doc/nst.1',
    'nst.1.adoc',
    action='a2x -f manpage -D ./doc $SOURCE'
)

# this is generated in the source tree!
nst_msg_man_cmd = doc_env.Command(
    '#doc/nst-msg.1',
    'nst-msg.1.adoc',
    action='a2x -f manpage -D ./doc $SOURCE'
)

# this is generated in the source tree!
nst_conf_man_cmd = doc_env.Command(
    '#doc/nst.conf.5',
    'nst.conf.5.adoc',
    action='a2x -f manpage -D ./doc $SOURCE'
)

env.Alias('man', nst_man_cmd)
env.Alias('man', nst_msg_man_cmd)
env.Alias('man', nst_conf_man_cmd)
