Import('env')

data_env = env.Clone()

# terminfo install tree

terminfo_dir = env['buildroot'] + '/data/terminfo'

tic_cmd = data_env.Command(
    'terminfo/n/nst',
    'nst.tinfo',
    action=[
        Mkdir(terminfo_dir),
        f'tic -o{terminfo_dir} -sx data/nst.tinfo'
    ]
)

env.Alias('install', tic_cmd)

# terminfo user based install

Default(tic_cmd)

tic_user_cmd = data_env.Command(
    None,
    'nst.tinfo',
    action='tic -sx data/nst.tinfo'
)

env.Alias('terminfo_user', tic_user_cmd)
env.AlwaysBuild(tic_user_cmd)
