Import('env')

warnings = ["all", "error", "extra", "null-dereference", "double-promotion", "shadow", "format=2"]
warnings = [f"-W{w}" for w in warnings]

env.ConfigureForPackage(["xft", "freetype2", "fontconfig", "x11", "tclap"])
env.ConfigureForLib("libcosmos")
env.Append(CCFLAGS=['-DVERSION=\\"1.16.0\\"', "-D_XOPEN_SOURCE=600"])
env.Append(LIBS=["util"])
env.Append(CCFLAGS=warnings)

sources = env.GatherSources(suffixes=[".cxx"])

nst = env.Program("nst", sources)

env['bins']['nst'] = nst
env.Alias("nst", nst)
