Import('env')

env.ConfigureForPackage(["xft", "freetype2", "fontconfig", "x11", "tclap"])
env.ConfigureForLib("libcosmos")
env.ConfigureForLib("libX++")
env.Append(CCFLAGS=['-DVERSION=\\"0.9\\"'])

sources = env.GatherSources(suffixes=[".cxx"])

nst = env.Program("nst", sources)

env['bins']['nst'] = nst
env.Alias("nst", nst)
