Import('env')

env.Append(CPPPATH=['#/tclap/include'])

sources = env.GatherSources(suffixes=[".cxx"])

env.ConfigureForLib("libX++", sources)
env.ConfigureForLib("libcosmos", sources)
env.ConfigureForPackage(["xft", "freetype2", "fontconfig", "x11", "tclap"])
env.Append(CCFLAGS=['-DVERSION=\\"0.9\\"'])

nst = env.Program("nst", sources)

env['bins']['nst'] = nst
env.Alias("nst", nst)
